name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install pm2
    - uses: actions/setup-node@v1
      with: 
        node-version: 12
      run: |
        npm install -g pm2
    - name: Run pm2
      run: |
        pm2 ecosystem.yaml product
